services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel-devy

    restart: unless-stopped
    ports:
      - "${BESZEL_HTTP}:8090"
    volumes:
      - ${BESZEL_DATA}:/beszel_data

    networks:
      - Homebox

networks:
  Homebox:
    name: ${HOMEBOX_NETWORK}
    external: true
